FROM node:20-alpine AS base
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* .npmrc* ./
COPY apps/frontend ./apps/frontend
RUN npm install --workspace apps/frontend
RUN npm run build --workspace apps/frontend

FROM nginx:stable-alpine
COPY --from=base /app/apps/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
