create table if not exists documents (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  created_at timestamp with time zone default timezone('utc', now())
);
